### ISSUE TITLE
Create Resources folder

### ISSUE THREAD

**Issue by ana-vela** [ana-vela/Today-I-Learned-Tracker#1]
If you'd like to work on this issue, please add a comment here so I know who is working on it. :)

Fork this repo and create a new branch to work on this issue. Once completed, make a pull request for review.

1. Add a new folder named Resources and add one new markdown file called CodingCourses.md
2. In the CodingCourses.md file, create a header called Coding Courses and add a bullet with one course name such as The Odin Project or CS 50. Make sure this is a clickable link like this:

* [ Free Code Camp](https://freecodecamp.org)

**Comment by phoebe-michel** [comment]
Hi! I'd like to work on this issue

**Comment by ana-vela** [comment]
Wonderful! Let me know if you have any questions. :) Thanks for your help, @awkwardblackcoder !

**Comment by jatin2003** [comment]
I'll love to take on this issue 🙂

**Comment by jatin2003** [comment]
I'll love to work on this issue, If @awkwardblackcoder is not working on this issue anymore 😊
